### ISSUE TITLE
Bug in the style.css media queries code for carousel codealong lab

### ISSUE THREAD

**Issue by glee38** [learn-co-curriculum/bootstrap-image-carousel-code-along#1]
The video's code for the style.css media queries in the carousel codealong lab was taught as follows:

```
/*/////// CAROUSEL STYLES ////////*/

#carousel-example.generic .item img {
  height: auto;
}

.carousel-caption p {
  display: none;
}

@media only screen and (min-width: 768px) {
  #carousel-example-generic .item img {
    height: 384px;
  }
}

@media only screen and (min-width: 992px) {
  #carousel-example.generic .item img {
    height: 496px;
  }
  .carousel-caption p {
    display: block;
  }
}

@media only screen and (min-width: 1200px) {
  #carousel-example.generic .item img {
    height: 600px;
  }
  .carousel-caption p {
    display: block;
  }
}
```

However, with this code, when I resized the width of my browser, the height of my carousel images did not change when increased from 768px to 992px to 1200px.

After looking through some of the files, the code with which I was able to get the carousel media queries to work properly was as follows:

```
/*/////// CAROUSEL STYLES ////////*/

#carousel-example.generic .item img {
  height: auto;
}

.carousel-caption p {
  display: none;
}

@media only screen and (min-width: 768px) {
  #carousel-example-generic .item img {
    height: 384px;
  }
}

@media only screen and (min-width: 992px) {
  #carousel-example.generic .item img {
    height: 496px;
  }
  .carousel-caption p {
    display: block;
  }


@media only screen and (min-width: 1200px) {
  #carousel-example.generic .item img {
    height: 600px;
  }
  .carousel-caption p {
    display: block;
  }
```

It only worked properly after I took out the curly braces on the last line of the last two media queries.

**Comment by jongrover** [comment]
Hi @glee38 your selectors should be #carousel-example-generic not #carousel-example.generic
Your dot before generic should be a dash. Here is the full solution:

``` css
/*////// CAROUSEL STYLES //////*/

#carousel-example-generic .item img {
  height: auto;
}

.carousel-caption p {
  display: none;
}

@media only screen and (min-width: 768px) {
  #carousel-example-generic .item img {
    height: 384px;
  }
}

@media only screen and (min-width: 992px) {
  #carousel-example-generic .item img {
    height: 496px;
  }
  .carousel-caption p {
    display: block;
  }
}

@media only screen and (min-width: 1200px) {
  #carousel-example-generic .item img {
    height: 600px;
  }
}
```
